### ISSUE TITLE
Problematic use of WebAssembly for Chrome

### ISSUE THREAD

**Issue by mislam** [pokt-network/pocket-js#36]
One of the dependencies of the `provider` package is `undici` that uses WASM (WebAssembly).

https://github.com/pokt-foundation/pocket-js-slim/blob/10efcca022682c806bc650fe0ef0c92a4da2edd9/packages/provider/package.json#L39

This is a problem specially for developing Chrome extensions, as Google is forcefully phasing out the Manifest v2 and forcing extension developers to use v3. This new policy is not allowing WebAssembly. I have tried it out myself. The code works on the browser. But when I'm using the same code to build a Chrome extension, it blocks WASM. It's a common known issue with Chrome Extension Manifest V3.

Please read this section from the article:

> Many of these issues are filed as bugs. According to Miagkov and Cyphers, observational webRequest, native messaging, background tasks, WebSockets, user script extensions, and **WebAssembly** are all broken under **Manifest v3** presently.

Source: https://www.theregister.com/2021/12/14/googles_manifest_v3_extension_plan/

Beside this issue, the `undici` package is also breaking the `provider` instantiating functionality. I already submitted an issue about this: https://github.com/pokt-foundation/pocket-js-slim/issues/35

Is there a way we could bypass using `undici` and other packages that use `wasm`?

**Comment by Evalir** [comment]
This will be possible with the `IsomorphicProvider` which will be included in a different package in a new release coming soon. We use undici on the `JsonRpcProvider` because it's faster than their isomorphic/browser-only versions. I wasn't aware this was chrome-extension breaking software though, so it's good to keep this in mind.

Also, note that the documentation for `JsonRpcProvider` explicitly states is node-only.

As the solution is laid out in this answer, I'll close this issue. However, feel free to open more. :)
