### ISSUE TITLE
Need a guideline for contribution

### ISSUE THREAD

**Issue by mislam** [pokt-network/pocket-js#37]
I found few major issues with some part of this project. One of them being the BigInt conversion. I would like to contribute to this project by working on those bugfixes. But I could not get the dev environment running.

When I ran (from the root of the project):

```
pnpm install
pnpm run dev
```

I get this error (in the midst of the build process):

```
pocket-js-slim/packages/abstract-provider/src/abstract-provider.ts(10,8): semantic error TS2307: Cannot find module '@pokt-foundation/pocketjs-types' or its corresponding type declarations.
```

I'm not sure if I am running the dev script properly! FYI, I'm only familiar with `npm`, and never used `pnpm` before. So I kinda assumed those two lines `pnpm install` and `pnpm run dev`.

If it requires further instructions to get the dev script running properly, I'd suggest to add those instructions in the README.

Thanks!

**Comment by Evalir** [comment]
Hey! Thanks for opening all of these issues; it helps us get to a stable release of the project. Always good to have more beta/alpha testers. However, please note that this is indeed beta software; issues outside the `relayer` are to be expected, and we're first tending to the internal needs of the Portal API.

We'll add the contribution guide along with more extensive docs between today and tomorrow, depending on our internal timelines for a few things, along with missing packages and types coming next week. It's possible that these bugfixes might be already in the works, but feel free to drop a few PRs!

To get the test environment running, after running `pnpm i` run `pnpm build`; the reason it doesn't work is that the dev environment in turborepo is run in parallel by default which means the packages that use other local dependencies don't wait for their parent dependencies to build. There's a fix for this coming, but for now you can just bypass everything by running `pnpm build`. This is mainly due to the fact that we've been internally testing this project using symlinks and actual deployments of it.

**Comment by Evalir** [comment]
Added in https://github.com/pokt-foundation/pocket-js/commit/b7543fc1769d012710c088e5baa6156d2cfdc102
