### ISSUE TITLE
[BUG REPORT] Import prtobufjs error

### ISSUE THREAD

**Issue by nodiesBlade** [pokt-network/pocket-js#79]
**Describe the bug**
I am unable to use the latest pocketjs version 2.1.0
```js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\iuhas\staker
\node_modules\@pokt-foundation\pocketjs-transaction-builder\node_modules\protobufjs\minimal' imported from C:\Users\iuhas\staker\node_modules\
@pokt-foundation\pocketjs-transaction-builder\dist\index.js
Did you mean to import protobufjs/minimal.js?
```
**To Reproduce**
```js
import fs from 'fs'
import {TransactionBuilder} from "@pokt-foundation/pocketjs-transaction-builder";
import {KeyManager} from "@pokt-foundation/pocketjs-signer";
import {IsomorphicProvider} from '@pokt-foundation/pocketjs-isomorphic-provider'
```
Just importing the modules will cause the error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Node: 16.14.0
 - PocketJS 2.1.0

**Additional context**
Package.json
```js
{
  "name": "staker",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@pokt-foundation/pocketjs-isomorphic-provider": "^2.1.0",
    "@pokt-foundation/pocketjs-provider": "^2.1.0",
    "@pokt-foundation/pocketjs-relayer": "^2.1.0",
    "@pokt-foundation/pocketjs-signer": "^2.1.0",
    "@pokt-foundation/pocketjs-transaction-builder": "^2.1.0",
    "@pokt-foundation/pocketjs-utils": "^2.1.0",
    "protobufjs": "4.1.3"
  }
}
```

**Comment by crisog** [comment]
I was able to reproduce this issue, it has to do when using ES modules in the NodeJS app.

The reason being that the file that brought this issue on the newer `v2.1.0` release is auto-generated by `protoc` library for protobuf models. We will try to reach out and see if there's a way to configure `protoc` so it can generate the models using imports that are compatible with ES modules.

https://github.com/pokt-foundation/pocket-js/blob/00e85a5c0b6a20ced85a3df7a12bb25004d691a9/packages/transaction-builder/src/models/proto/generated/tx-signer.ts#L8

While this gets fixed, you can still use the library using any of these options:

1) Run the app using this flag `node --es-module-specifier-resolution=node index.js`
2) Use regular import (no ES modules)
```javascript
const { TransactionBuilder } = require("@pokt-foundation/pocketjs-transaction-builder");
```
3) Write your script using typescript/`ts-node` instead of `node`.

We'll work on a release to make sure it fully works with ES modules out of the box.

**Comment by crisog** [comment]
Turns out the plugin we are using to generate the protos is not node ESM friendly. It's been an open issue for around a year.
https://github.com/stephenh/ts-proto/issues/338

**Comment by paralin** [comment]
It's compatible. Enable esModuleInterop and importSuffix=.js in the ts-proto opts.
